### PR TITLE
Rework python packaging.

### PR DESCRIPTION
**Pull request by mithro**
* Move `setup.py` and `pyproject.toml` to root directory otherwise everything breaks.
 * Use `setuptool_scm` for version.
 * Build wheels from sdist files using pip.

### CODE REVIEW

**Comment by mithro** [comment]
@litghost - I believe this is ready to be merged now. The windows API builds now work.

**Comment by litghost** [comment]
> @litghost - I believe this is ready to be merged now. The windows API builds now work.

Looks like Mac OS is failing?  I recommend you push this branch with only Ubuntu and Windows, and get it merged.  Once that is done, follow up with Mac OS fix?  Otherwise LGTM!

**Comment by litghost** [comment]
Error on Mac OS looks easy enough to fix:
```
+ which swig
Error: Process completed with exit code 1.
```

**Comment by mithro** [comment]
I disable MacOS for now. For some reason on my repository I get;
```
test_macosx (11, xcode, Release, macos-11.0, shared64 static64)
No runner matching the specified labels was found: macos-11.0.
```

**Pull request merged**
